template <int lane>[[gnu::always_inline]] nce int32_t duplicate_lane(int32x2_t vec) { return vdups_lane_s32(vec, lane); }
template <int lane>[[gnu::always_inline]] nce int32_t duplicate_lane(int32x4_t vec) { return vdups_laneq_s32(vec, lane); }
template <int lane>[[gnu::always_inline]] nce uint32_t duplicate_lane(uint32x2_t vec) { return vdups_lane_u32(vec, lane); }
template <int lane>[[gnu::always_inline]] nce uint32_t duplicate_lane(uint32x4_t vec) { return vdups_laneq_u32(vec, lane); }
template <int lane>[[gnu::always_inline]] nce float32_t duplicate_lane(float32x2_t vec) { return vdups_lane_f32(vec, lane); }
template <int lane>[[gnu::always_inline]] nce float32_t duplicate_lane(float32x4_t vec) { return vdups_laneq_f32(vec, lane); }
template <int lane>[[gnu::always_inline]] nce uint8_t duplicate_lane(uint8x8_t vec) { return vdupb_lane_u8(vec, lane); }
template <int lane>[[gnu::always_inline]] nce uint8_t duplicate_lane(uint8x16_t vec) { return vdupb_laneq_u8(vec, lane); }
template <int lane>[[gnu::always_inline]] nce int8_t duplicate_lane(int8x8_t vec) { return vdupb_lane_s8(vec, lane); }
template <int lane>[[gnu::always_inline]] nce int8_t duplicate_lane(int8x16_t vec) { return vdupb_laneq_s8(vec, lane); }
template <int lane>[[gnu::always_inline]] nce poly8_t duplicate_lane(poly8x8_t vec) { return vdupb_lane_p8(vec, lane); }
template <int lane>[[gnu::always_inline]] nce poly8_t duplicate_lane(poly8x16_t vec) { return vdupb_laneq_p8(vec, lane); }
template <int lane>[[gnu::always_inline]] nce uint16_t duplicate_lane(uint16x4_t vec) { return vduph_lane_u16(vec, lane); }
template <int lane>[[gnu::always_inline]] nce uint16_t duplicate_lane(uint16x8_t vec) { return vduph_laneq_u16(vec, lane); }
template <int lane>[[gnu::always_inline]] nce int16_t duplicate_lane(int16x4_t vec) { return vduph_lane_s16(vec, lane); }
template <int lane>[[gnu::always_inline]] nce int16_t duplicate_lane(int16x8_t vec) { return vduph_laneq_s16(vec, lane); }
template <int lane>[[gnu::always_inline]] nce float16_t duplicate_lane(float16x4_t vec) { return vduph_lane_f16(vec, lane); }
template <int lane>[[gnu::always_inline]] nce float16_t duplicate_lane(float16x8_t vec) { return vduph_laneq_f16(vec, lane); }
template <int lane>[[gnu::always_inline]] nce poly16_t duplicate_lane(poly16x4_t vec) { return vduph_lane_p16(vec, lane); }
template <int lane>[[gnu::always_inline]] nce poly16_t duplicate_lane(poly16x8_t vec) { return vduph_laneq_p16(vec, lane); }
