name: tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main


jobs:
  test-build-arm:
    name: Run tests (ARM64)
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Use GCC 14
        run: |
          echo "CC=gcc-14" >> $GITHUB_ENV
          echo "CXX=g++-14" >> $GITHUB_ENV
        if: matrix.compiler == 'gcc'

      - name: Use Clang
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        if: matrix.compiler == 'clang'

      - name: Configure
        run: cmake -B build -DARGON_ENABLE_TESTING=YES

      - name: Run build
        run: cmake --build build

      - name: Run CTest
        run: ctest --output-on-failure --test-dir build/test/specs

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Results (ARM64 ${{ matrix.compiler }})
          path: |
            build/test/specs/results/*.xml
            build/test/specs/results/**/*.xml

  test-build-qemu:
    name: Run tests (ARMv7/QEMU)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install cross-compilation toolchain and QEMU
        run: |
          sudo debconf-communicate <<< "set man-db/auto-update false"
          sudo dpkg-reconfigure man-db
          sudo apt-get update
          sudo apt-get install -y gcc-14-arm-linux-gnueabihf g++-14-arm-linux-gnueabihf qemu-user binfmt-support qemu-user-static qemu-system-arm
          echo "CC=arm-linux-gnueabihf-gcc-14" >> $GITHUB_ENV
          echo "CXX=arm-linux-gnueabihf-g++-14" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Symlink ld-linux
        run: sudo ln -s /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 /lib/ld-linux-armhf.so.3

      - name: Configure
        run: cmake -B build -G Ninja -DARGON_ENABLE_TESTING=YES -DARGON_TEST_QEMU=YES

      - name: Run build
        run: cmake --build build

      - name: Run CTest
        run: ctest --output-on-failure --test-dir build/test/specs

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Results (ARMv7)
          path: |
            build/test/specs/results/*.xml
            build/test/specs/results/**/*.xml

  test-build-x86_64-linux:
    name: Run tests (x86_64 Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Use GCC 14
        run: |
          echo "CC=gcc-14" >> $GITHUB_ENV
          echo "CXX=g++-14" >> $GITHUB_ENV
        if: matrix.compiler == 'gcc'

      - name: Use Clang
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        if: matrix.compiler == 'clang'

      - name: Configure
        run: cmake -B build -DARGON_ENABLE_TESTING=YES

      - name: Run build
        run: cmake --build build

      - name: Run CTest
        run: ctest --output-on-failure --test-dir build/test/specs

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Results (x86 Linux ${{ matrix.compiler }})
          path: |
            build/test/specs/results/*.xml
            build/test/specs/results/**/*.xml


  test-build-x86_64-windows:
    name: Run tests (x86_64 Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -G "Visual Studio 17 2022" -A x64 -T ClangCL -B build -DARGON_ENABLE_TESTING=YES -DCMAKE_BUILD_TYPE=Release

      - name: Run build
        run: cmake --build build

      - name: Run CTest
        run: ctest --output-on-failure --test-dir build/test/specs -C Release

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Results (x86 Windows)
          path: |
            build/test/specs/results/*.xml
            build/test/specs/results/**/*.xml

  publish-test-results:
    name: "Publish Tests Results"
    needs:
      - test-build-arm
      - test-build-qemu
      - test-build-x86_64-linux
      - test-build-x86_64-windows
    runs-on: ubuntu-latest
    permissions:
      checks: write

      # only needed unless run with comment_mode: off
      pull-requests: write

    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.xml"
